---
- name: Check for validate_password plugin
  shell: mysql -NBe 'SHOW PLUGINS;'
  register: mysql_show_plugins
  when: mysql_uninstall_validate_password
  changed_when: false

- name: Uninstall validate_password plugin
  shell: mysql -NBe 'UNINSTALL PLUGIN validate_password;'
  when: mysql_uninstall_validate_password and 'validate_password' in mysql_show_plugins.stdout
